name: Bug
description: Add Bug
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: input
    id: odoo_task_id
    attributes:
      label: Odoo Task Id
      description: id of task on Odoo
    validations:
      required: false
  - type: input
    id: odoo_helpdesk_id
    attributes:
      label: Odoo Helpdesk Ticket Id
      description: id of helpdesk ticket on Odoo
    validations:
      required: false
  - type: textarea
    id: external_url
    attributes:
      label: External URL
      description: External URL on other tracker
    validations:
      required: false
  - type: dropdown
    id: env
    attributes:
      label: Environnement
      multiple: true
      options:
        - Prod
        - Staging
        - Local
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error
      description: Error message or traceback
      render: shell
    validations:
      required: true
