name: Bug
description: bug/issue
title: "[BUG] <title>"
labels: ["Bug"]
body:
  - type: input
    id: odoo_task_id
    attributes:
      label: Odoo Task Id
      description: id of task on Odoo
    validations:
      required: false
  - type: input
    id: external_url
    attributes:
      label: External URL
      description: External URL on other tracker
    validations:
      required: false
- type: dropdown
  id: env
  attributes:
    label: Environnement
    multiple: true
    options:
      - Prod
      - Staging
      - Local
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Description
  validations:
    required: true
- type: textarea
  attributes:
    label: Error
    description: Error message or traceback
    render: shell
  validations:
    required: true