name: Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [Bug, Needs Triage]
body:
- type: dropdown
  id: env
  attributes:
    label: Environnement
    multiple: true
    options:
      - Prod
      - Staging
      - Local
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: Description
  validations:
    required: true
- type: textarea
  attributes:
    label: Error
    description: Error message or traceback
    render: shell
  validations:
    required: true