name: Feature
description: Add Feature
title: "[FEATURE] <title>"
labels: ["enhancement"]
body:
  - type: input
    id: odoo_task_id
    attributes:
      label: Odoo Task Id
      description: id of task on Odoo
    validations:
      required: false
  - type: input
    id: odoo_helpdesk_id
    attributes:
      label: Odoo Helpdesk Id
      description: id of helpdesk ticket on Odoo
    validations:
      required: false
  - type: textarea
    id: external_url
    attributes:
      label: External URL
      description: External URL on other tracker
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: Type of feature
      multiple: true
      options:
        - Configurator
        - Specific Module
        - Generic Module
  - type: input
    attributes:
      label: Module
      description: Work module
    validations:
      required: false
  - type: input
    attributes:
      label: Model
      description: Model to create or modify
    validations:
      required: false
  - type: dropdown
    id: option
    attributes:
      label: Type of developpement
      multiple: true
      options:
        - Field
        - Constraint
        - Model
        - Menu
        - View Form
        - View Tree
        - View Search
        - View Kanban
        - View Other
        - Wizard Button
        - Wizard Multi
        - Wizard Menu
        - Action
        - Hook
        - Onchange
        - Access
        - Rule
        - PDF
        - Controller
        - Front View
        - Other
  - type: textarea
    attributes:
      label: Description
      description: Description
    validations:
      required: false
  - type: textarea
    attributes:
      label: Tests
      description: Tests
    validations:
      required: false

